name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./client

    - name: Build the app
      run: npm run build
      working-directory: ./client

    - name: Dockerize the app
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/chai-dapp-frontend:latest ./client
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/chai-dapp-frontend:latest

    - name: Deploy to AWS EKS
      uses: aws-actions/eks-eksctl@v0.1.0
      with:
        cluster-name: Chai_Dapp
        region: es-east-1
        role-to-assume: arn:aws:iam::975049908225:role/Chai_Dapp-cluster-20240717200422471100000003

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/frontend frontend=${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
